In [14]:
import pandas as pd
import numpy as np
import pickle
from sklearn import metrics
from sklearn import preprocessing

In [15]:
class testing():
    
    df = pd.DataFrame()
    scaled_X = pd.DataFrame()
    y = []
    model = ''
    y_pred = []
    
    def __init__(self, filename):
        self.df = pd.read_csv(filename)
        print(f"Read the python {filename} file ")
        
    def display(self):
        display(self.df.head())
        
    def list_columns(self):
        display(self.df.columns)
        
    def renaming_columns(self):
        self.df.columns = self.df.columns.str.strip()
        print("Stripped leading whitespaces in column names")
        self.df = self.df.rename(columns = {'dx':'target'})
        print("Renamed the column name from 'dx' to 'target'")
        display(self.df.columns)
        
    def checking_imbalance(self):
        display(self.df['target'].value_counts())
        
    def basic_analysis(self):
        print("Chracteristics of the data is")
        display(self.df.describe())
        print("Shape of the data is")
        display(self.df.shape)
        
    def feature_engineering(self):
        self.df = self.df.assign(diff_f2_f1=self.df['meanf2'] - self.df['meanf1'])
        print("Subtracting formant f2 and f1 for the whole utterance ")
        self.df.insert(6, 'diff_f2_f1', self.df.pop('diff_f2_f1'))
        print("Inserting the column in different position")
        display(self.df.head())
        
    def scale_data(self):
        X = self.df.drop(columns=['target']).copy()
        self.y = self.df['target']
        scaler = preprocessing.MinMaxScaler()
        self.scaled_X = df = pd.DataFrame(scaler.fit_transform(X))
        print("Scaled data using MinMaxScaler")
        display(self.scaled_X.head())
        
    def load_model(self):
        self.model = pickle.load(open('training_model2.pkl', 'rb'))
        print("Model loaded successfully")
    
    def test_model(self):
        print("Testing the loaded model")
        self.y_pred = self.model.predict(self.scaled_X)
        
    def print_metrics(self):
        # using metrics module for accuracy calculation
        print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(self.y, self.y_pred))
        print(metrics.classification_report(self.y, self.y_pred))
        print("Confusion Matrix")
        print(metrics.confusion_matrix(self.y, self.y_pred))

In [16]:
obj = testing("testdialectsdataoutput2.csv")

Read the python testdialectsdataoutput2.csv file

In [17]:
obj.display()

,maxint,meanint,maxf1,meanf1,maxf2,meanf2,maxpitch,meanpitch,maxharmonicity,meanharmonicity,numberofpulses,numberofperiods,jitter,shimmer,unvoicedframes,voicebreaks,meanautocorrelation,meannoisetoharmonicsratio,meanharmonicstonoiseratio,dx
0,85.738058,67.090647,3476.936814,1075.212098,4075.189847,2131.542017,595.249945,128.303092,46.651162,7.595803,1001,855,0.03011,0.11931,0.55483,68,0.837884,0.228043,8.673,0
1,80.942235,70.196170,2628.242985,709.501167,3918.780700,1898.349993,589.445993,107.710792,39.848391,8.253267,1257,1189,0.02397,0.12305,0.42649,55,0.862064,0.190037,10.110,0
2,81.202956,71.195914,2578.375462,822.241135,4034.263124,1999.111403,535.464402,137.953593,40.027690,7.123437,1380,1309,0.02645,0.10253,0.53000,57,0.865544,0.187909,10.369,0
3,82.789537,73.550377,2956.954099,696.461238,3710.933124,2052.413186,598.645559,228.334549,45.246234,13.026792,2403,2291,0.01897,0.07526,0.40566,64,0.923390,0.107473,15.386,0
4,78.366569,64.769550,2407.636271,678.498772,3317.733739,1893.370839,624.279385,199.265633,58.118430,9.054496,1650,1571,0.02013,0.12318,0.50875,55,0.858522,0.198586,9.574,0

In [18]:
obj.list_columns()

Index(['maxint', 'meanint', 'maxf1', 'meanf1', 'maxf2', 'meanf2', ' maxpitch',
       ' meanpitch', ' maxharmonicity', ' meanharmonicity', ' numberofpulses',
       ' numberofperiods', ' jitter', ' shimmer', ' unvoicedframes',
       ' voicebreaks', ' meanautocorrelation', ' meannoisetoharmonicsratio',
       ' meanharmonicstonoiseratio', ' dx'],
      dtype='object')

In [19]:
obj.renaming_columns()

Stripped leading whitespaces in column names
Renamed the column name from 'dx' to 'target'

Index(['maxint', 'meanint', 'maxf1', 'meanf1', 'maxf2', 'meanf2', 'maxpitch',
       'meanpitch', 'maxharmonicity', 'meanharmonicity', 'numberofpulses',
       'numberofperiods', 'jitter', 'shimmer', 'unvoicedframes', 'voicebreaks',
       'meanautocorrelation', 'meannoisetoharmonicsratio',
       'meanharmonicstonoiseratio', 'target'],
      dtype='object')

In [20]:
obj.checking_imbalance()

0    8
1    8
Name: target, dtype: int64

In [21]:
obj.basic_analysis()

Chracteristics of the data is

,maxint,meanint,maxf1,meanf1,maxf2,meanf2,maxpitch,meanpitch,maxharmonicity,meanharmonicity,numberofpulses,numberofperiods,jitter,shimmer,unvoicedframes,voicebreaks,meanautocorrelation,meannoisetoharmonicsratio,meanharmonicstonoiseratio,target
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.0000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000
mean,82.786819,70.415798,2796.960158,749.590065,3786.038725,1922.011692,566.720274,155.847674,45.520570,9.078821,1826.312500,1738.4375,0.022782,0.112763,0.454654,59.125000,0.861334,0.197885,10.367562,0.500000
std,2.341428,3.186346,331.363217,112.046856,245.236852,94.842130,63.906530,38.902187,6.191945,2.153226,640.317704,632.9160,0.004354,0.021694,0.056326,9.061825,0.033692,0.052339,2.293300,0.516398
min,78.366569,64.769550,2349.107645,579.496585,3317.733739,1764.294067,375.305299,107.710792,38.104621,6.865636,1001.000000,855.0000,0.015560,0.075260,0.368120,43.000000,0.798520,0.107473,7.358000,0.000000
25%,81.137776,69.198056,2566.617603,692.136727,3628.914112,1875.638097,575.793413,131.521143,40.383738,7.716916,1344.000000,1271.2500,0.019960,0.095825,0.420320,54.000000,0.837568,0.168510,8.637000,0.000000
50%,82.962913,71.088897,2666.931683,717.976625,3877.629886,1907.636785,591.865656,142.736388,44.044955,8.428200,1566.000000,1478.0000,0.022400,0.119885,0.444120,59.500000,0.859970,0.199287,9.989000,0.500000
75%,83.995460,72.507537,3032.022292,797.782103,3955.934692,1975.884421,595.747261,180.740115,48.388785,9.317888,2352.750000,2266.2500,0.026760,0.128485,0.503065,65.000000,0.877698,0.229127,10.993250,1.000000
max,86.983905,75.769593,3476.936814,1075.212098,4075.189847,2131.542017,624.279385,228.334549,58.118430,14.442173,2976.000000,2883.0000,0.030110,0.142060,0.554830,74.000000,0.923390,0.305772,15.386000,1.000000

Shape of the data is

(16, 20)

In [22]:
obj.feature_engineering()

Subtracting formant f2 and f1 for the whole utterance
Inserting the column in different position

,maxint,meanint,maxf1,meanf1,maxf2,meanf2,diff_f2_f1,maxpitch,meanpitch,maxharmonicity,...,numberofpulses,numberofperiods,jitter,shimmer,unvoicedframes,voicebreaks,meanautocorrelation,meannoisetoharmonicsratio,meanharmonicstonoiseratio,target
0,85.738058,67.090647,3476.936814,1075.212098,4075.189847,2131.542017,1056.329919,595.249945,128.303092,46.651162,...,1001,855,0.03011,0.11931,0.55483,68,0.837884,0.228043,8.673,0
1,80.942235,70.196170,2628.242985,709.501167,3918.780700,1898.349993,1188.848826,589.445993,107.710792,39.848391,...,1257,1189,0.02397,0.12305,0.42649,55,0.862064,0.190037,10.110,0
2,81.202956,71.195914,2578.375462,822.241135,4034.263124,1999.111403,1176.870268,535.464402,137.953593,40.027690,...,1380,1309,0.02645,0.10253,0.53000,57,0.865544,0.187909,10.369,0
3,82.789537,73.550377,2956.954099,696.461238,3710.933124,2052.413186,1355.951948,598.645559,228.334549,45.246234,...,2403,2291,0.01897,0.07526,0.40566,64,0.923390,0.107473,15.386,0
4,78.366569,64.769550,2407.636271,678.498772,3317.733739,1893.370839,1214.872068,624.279385,199.265633,58.118430,...,1650,1571,0.02013,0.12318,0.50875,55,0.858522,0.198586,9.574,0

In [23]:
obj.scale_data()

Scaled data using MinMaxScaler

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.855426,0.211008,1.000000,1.000000,1.000000,1.000000,0.000000,0.883404,0.170715,0.427032,0.096372,0.000000,0.000000,1.000000,0.659431,1.000000,0.806452,0.315240,0.608021,0.163802
1,0.298894,0.493327,0.247498,0.262256,0.793507,0.365028,0.442287,0.860092,0.000000,0.087128,0.183148,0.129620,0.164694,0.578007,0.715419,0.312624,0.387097,0.508881,0.416361,0.342800
2,0.329149,0.584213,0.203282,0.489685,0.945968,0.639397,0.402308,0.643276,0.250720,0.096087,0.034026,0.191899,0.223866,0.748454,0.408234,0.867013,0.451613,0.536750,0.405630,0.375062
3,0.513264,0.798254,0.538953,0.235951,0.519105,0.784536,1.000000,0.897042,1.000000,0.356834,0.813189,0.709873,0.708087,0.234364,0.000000,0.201060,0.677419,1.000000,0.000000,1.000000
4,0.000000,0.000000,0.051895,0.199716,0.000000,0.351470,0.529140,1.000000,0.759012,1.000000,0.288900,0.328608,0.353057,0.314089,0.717365,0.753200,0.387097,0.480516,0.459473,0.276034

In [24]:
obj.load_model()

Model loaded successfully

In [25]:
obj.test_model()

Testing the loaded model

In [26]:
obj.print_metrics()

ACCURACY OF THE MODEL:  0.6875
              precision    recall  f1-score   support

           0       0.71      0.62      0.67         8
           1       0.67      0.75      0.71         8

    accuracy                           0.69        16
   macro avg       0.69      0.69      0.69        16
weighted avg       0.69      0.69      0.69        16

Confusion Matrix
[[5 3]
 [2 6]]